/**
 * LLM model abstraction — OpenAI-compatible chat completions.
 * FIRERAID_LLM_BASE_URL, FIRERAID_LLM_API_KEY, FIRERAID_LLM_MODEL
 * FIX: Accept temperature and max_tokens from manifest (FR-R3-038).
 * FIX: Use AbortController for network timeout (FR-R3-037).
 * FR-P0-9: callLlm returns { content, provenance } — the runner records what
 *   was REQUESTED (model id, temperature, max_tokens) alongside what the
 *   provider actually SERVED (`model` + `provider` in the response). An
 *   OpenRouter-style router may alias the requested id to a different
 *   backend; only the served id is honest provenance.
 * FR-P0-10: base URL path normalization — a configured base of
 *   "https://host" AND "https://host/v1" both yield ".../v1/chat/completions"
 *   (a bare "/chat/completions" append on an already-versioned base is the
 *   classic 404).
 * FR-P0-11: harness/.env is loaded here (attack-plane credentials live ONLY
 *   in the harness; src/ never sees them). dotenv-default semantics: real
 *   environment wins over .env, so CI-injected secrets are never shadowed by
 *   a stale file.
 */
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

export interface LlmConfig {
  temperature?: number;
  maxTokens?: number;
}

/** FR-P0-9: requested-vs-served record of one completion call. */
export interface LlmProvenance {
  /** URL the request was POSTed to (post-normalization). */
  endpoint: string;
  /** Model id we asked for (scenario/manifest value). */
  modelRequested: string;
  /** Model id the provider says it served. */
  modelServed?: string;
  /** Upstream provider host the router picked (OpenRouter `provider`). */
  providerOrigin?: string;
  /** Pool provider id when the serving provider came from the pool. */
  poolProvider?: string;
  temperature?: number;
  maxTokens?: number;
}

export interface LlmResult {
  content: string;
  provenance: LlmProvenance;
}

/**
 * FR-P0-11: parse harness/.env into the environment without clobbering real
 * env vars (dotenv default semantics: existing process.env wins). Called
 * once per process; missing file is a no-op.
 */
let envLoaded = false;
export function loadHarnessEnv(): void {
  if (envLoaded) return;
  envLoaded = true;
  const path = join(process.cwd(), "harness", ".env");
  if (!existsSync(path)) return;
  let text: string;
  try {
    text = readFileSync(path, "utf-8");
  } catch {
    return;
  }
  for (const rawLine of text.split("\n")) {
    const line = rawLine.trim();
    if (line === "" || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key in process.env) continue; // real environment wins
    process.env[key] = value;
  }
}

/**
 * FR-P0-10: normalize a configured base URL to "<scheme>/<host>/v1".
 * Accepts "https://host", "https://host/", "https://host/v1", "https://host/v1/".
 */
export function normalizeBaseUrl(baseUrl: string): string {
  const trimmed = baseUrl.replace(/\/+$/, "");
  return trimmed.endsWith("/v1") ? trimmed : `${trimmed}/v1`;
}

/** Retryable free-tier transport failures (availability, not our bug). */
function isTransientLlmError(err: unknown): boolean {
  if (!(err instanceof Error)) return false;
  // HTTP 408/429/5xx from the router; timeouts; empty-router responses.
  const status = err.message.match(/^LLM error: (\d{3})$/);
  if (status) return ["408", "429", "500", "502", "503", "504"].includes(status[1]);
  return err.message === "MODEL_TIMEOUT" || err.message === "LLM_EMPTY_REPLY";
}

// ---------------------------------------------------------------------------
// P1-POOL: provider pool (crush-config transfer) with same-model rotation.
//
// The pool file (harness/.llm-pool.json, gitignored, 0600) is generated by
// scripts/transfer-crush-providers.mjs from the user's crush config. The
// PRIMARY triple (FIRERAID_LLM_BASE_URL/API_KEY/MODEL) always wins when
// configured — the pool is fallback + rotation for free-tier 429/5xx
// flakiness, which is what blocked the pilot's LLM attack cells.
//
// Rotation policy — model id is trial identity (trialKey includes it):
//   1. Same-model rotation is AUTOMATIC: any pool provider advertising the
//      requested model id may serve a transient-failure retry. The model
//      under test never changes, so provenance honesty is intact.
//   2. Cross-model substitution is OPT-IN (FIRERAID_POOL=substitute): a
//      final fallback may serve a DIFFERENT advertised model from the pool.
//      This changes what the trial measures — it is a degraded-mode
//      convenience, never a silent one (the served id + pool id are always
//      recorded provenance).
//   3. FIRERAID_POOL=off disables the pool entirely (reproducibility runs).
// ---------------------------------------------------------------------------

interface PoolEntry {
  baseUrl: string;
  apiKey: string;
  models: string[];
  probe?: { status?: string };
}

interface PoolState {
  entries: PoolEntry[];
  /** In-process dead marks — a provider that 401/403s mid-run is not
   * retried within this process (probe state refreshes only via the
   * transfer script, deliberately out-of-band). */
  dead: Set<string>;
  /** Errors rotated through so far (for a final summary log line). */
  rotations: number;
}

let poolState: PoolState | null = null;

/** FIRERAID_POOL mode for this process: "off" | "same-model" (default) | "substitute". */
export type PoolMode = "off" | "same-model" | "substitute";
export function poolMode(): PoolMode {
  const v = (process.env.FIRERAID_POOL ?? "").trim().toLowerCase();
  if (v === "off") return "off";
  if (v === "substitute") return "substitute";
  return "same-model";
}

/** Load + cache the pool file. Returns null when absent/disabled/unusable. */
function getPool(): PoolState | null {
  if (poolMode() === "off") return null;
  if (poolState) return poolState;
  poolState = { entries: [], dead: new Set(), rotations: 0 };
  const path = join(process.cwd(), "harness", ".llm-pool.json");
  if (!existsSync(path)) return poolState;
  try {
    const raw = JSON.parse(readFileSync(path, "utf-8")) as {
      providers?: Record<string, PoolEntry>;
    };
    const entries: PoolEntry[] = [];
    for (const [id, p] of Object.entries(raw.providers ?? {})) {
      // Probe-dead entries (401/403 at transfer time) never enter rotation;
      // "auth-ok-shape"/"auth-ok-rate" entries DO — their key is valid.
      if (p.probe?.status === "dead" || p.probe?.status === "transport-error") continue;
      if (!p.baseUrl || !p.apiKey) continue;
      entries.push({ baseUrl: p.baseUrl, apiKey: p.apiKey, models: p.models ?? [] });
      // Remember the id on the entry for provenance (non-enumerable so the
      // object shape stays identical to file entries).
      Object.defineProperty(entries[entries.length - 1], "poolId", { value: id, enumerable: false });
    }
    poolState.entries = entries;
  } catch {
    // Malformed pool file → empty pool, primary-only behavior.
  }
  return poolState;
}

/** The pool id of an entry (set at load; "pool:<n>" fallback). */
function poolIdOf(e: PoolEntry): string {
  const id = (e as PoolEntry & { poolId?: string }).poolId;
  return typeof id === "string" ? id : "pool:unknown";
}

export interface ResolvedEndpoint {
  baseUrl: string;
  apiKey: string;
  /** Pool provider id when resolved from the pool; undefined = primary. */
  poolProvider?: string;
  /** Advertised model ids (pool entries only) — substitute mode serves
   * the first when the requested id isn't among them. */
  models?: string[];
}

/** Mark a pool provider dead for this process (auth rejection mid-run). */
export function markPoolProviderDead(poolProvider: string | undefined): void {
  if (!poolProvider) return;
  const pool = getPool();
  if (!pool) return;
  pool.dead.add(poolProvider);
  console.warn(`[llm-pool] provider ${poolProvider} marked DEAD for this process (auth rejection)`);
}

/**
 * P1-AUDIT-2 Phase F: bounded retry for FREE-TIER transport flakiness —
 * routers rate-limit (429) and providers shed load (5xx) between rounds.
 * Fixed short backoff keeps a smoke step under its timeout; MODEL_TIMEOUT
 * retries only when the backoff budget allows. A call that exhausts retries
 * throws the LAST error — the adapter's fail-closed mapping is unchanged.
 */
const LLM_RETRY_DELAYS_MS = [1500, 4000, 9000];

/**
 * P1-POOL: build the ordered candidate list for ONE call. Index 0 is the
 * PRIMARY triple when configured. Pool providers follow: same-model
 * advertisers first, then (substitute mode only) other providers with
 * their advertised model. Process-dead entries are excluded.
 * Under requireConfigured, throws only when the TOTAL candidate list is
 * empty — a configured pool covers an unconfigured primary.
 */
export function resolveLlmCandidates(
  requestedModel: string,
  opts: { requireConfigured?: boolean } = {}
): ResolvedEndpoint[] {
  loadHarnessEnv();
  const primary: ResolvedEndpoint[] =
    process.env.FIRERAID_LLM_BASE_URL && process.env.FIRERAID_LLM_API_KEY
      ? [{ baseUrl: process.env.FIRERAID_LLM_BASE_URL, apiKey: process.env.FIRERAID_LLM_API_KEY }]
      : [];
  const pool = getPool();
  if (!pool || pool.entries.length === 0) {
    if (primary.length === 0 && opts.requireConfigured) {
      throw new Error("LLM not configured — set FIRERAID_LLM_BASE_URL and FIRERAID_LLM_API_KEY");
    }
    return primary;
  }

  const out: ResolvedEndpoint[] = [...primary];
  // Same-model rotation first — the model under test never changes.
  for (const e of pool.entries) {
    if (pool.dead.has(poolIdOf(e))) continue;
    if (e.models.includes(requestedModel)) {
      out.push({ baseUrl: e.baseUrl, apiKey: e.apiKey, poolProvider: poolIdOf(e), models: e.models });
    }
  }
  // Opt-in substitution: providers advertising ANY model (serve their first).
  if (poolMode() === "substitute") {
    for (const e of pool.entries) {
      if (pool.dead.has(poolIdOf(e))) continue;
      if (e.models.includes(requestedModel)) continue; // already listed
      if (out.some((c) => c.baseUrl === e.baseUrl)) continue;
      out.push({ baseUrl: e.baseUrl, apiKey: e.apiKey, poolProvider: poolIdOf(e), models: e.models });
    }
  }
  if (out.length === 0 && opts.requireConfigured) {
    throw new Error("LLM not configured — set FIRERAID_LLM_BASE_URL and FIRERAID_LLM_API_KEY");
  }
  return out;
}

/**
 * P1-POOL completion core — one bounded walk over the candidate list,
 * shared by callLlm and callLlmVision. Attempt i uses candidate
 * min(i, candidates.length-1): with no pool this retries the PRIMARY
 * exactly as the pre-pool retry loop did; with a pool each candidate is
 * tried in order before any is retried.
 *
 * Per-candidate failure classes:
 *   - 401/403            → candidate marked process-dead, walk continues
 *                          (auth is not transient, but is candidate-local;
 *                          a PRIMARY auth failure also just fails its slot)
 *   - 402/400/404 from a POOL candidate → candidate-local (model id /
 *                          quota shape differs per provider); walk continues
 *   - 402/400/404 from the PRIMARY → hard error, immediate throw (the
 *                          pre-pool fail-closed behavior is preserved)
 *   - 408/429/5xx/timeout/empty → transient, advance with backoff
 * Provenance always reflects the endpoint that actually served.
 */
async function completeWithPool(
  requestedModel: string,
  buildBody: (servingModel: string) => string,
  parseContent: (json: unknown) => string | null,
  opts: { requireConfigured: boolean; timeoutMs: number; temperature: number; maxTokens: number }
): Promise<LlmResult> {
  const candidates = resolveLlmCandidates(requestedModel, { requireConfigured: opts.requireConfigured });
  // Total attempts is always 1 primary + one delay per retry slot (4),
  // independent of pool size. Pool rotation still walks candidates in
  // order, pinning the last candidate for retries: when fewer than 4
  // candidates exist the last one absorbs the extra attempts.
  const maxAttempts = 1 + LLM_RETRY_DELAYS_MS.length;
  let lastErr: unknown;

  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    if (attempt > 0) {
      const delay = LLM_RETRY_DELAYS_MS[attempt - 1];
      console.warn(`[llm] transient failure (${String(lastErr).slice(0, 80)}); next candidate in ${delay}ms`);
      await new Promise((r) => setTimeout(r, delay));
    }
    // Walk candidates in order; when the candidate list is shorter than
    // the attempt budget the LAST candidate absorbs the remaining retries
    // (no-pool behavior: primary retried with identical delays).
    const candidate = candidates[Math.min(attempt, candidates.length - 1)];
    const isPrimary = candidate.poolProvider === undefined;

    // Substitute mode only: serve a model the candidate actually
    // advertises. Same-model candidates and the primary serve the
    // requested id unchanged.
    const servingModel =
      candidate.poolProvider !== undefined &&
      candidate.models !== undefined &&
      candidate.models.length > 0 &&
      !candidate.models.includes(requestedModel)
        ? candidate.models[0]
        : requestedModel;

    const endpoint = `${normalizeBaseUrl(candidate.baseUrl)}/chat/completions`;
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), opts.timeoutMs);

    try {
      const resp = await fetch(endpoint, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: `Bearer ${candidate.apiKey}`,
        },
        body: buildBody(servingModel),
        signal: controller.signal,
      });

      if (!resp.ok) {
        const err = new Error(`LLM error: ${resp.status}`);
        const authRejected = resp.status === 401 || resp.status === 403;
        const candidateLocal = authRejected || resp.status === 402 || resp.status === 400 || resp.status === 404;
        if (candidateLocal && !isPrimary) {
          if (authRejected) markPoolProviderDead(candidate.poolProvider);
          lastErr = err;
          continue; // candidate-local failure — next candidate, same budget
        }
        throw err; // primary hard error, or non-local HTTP failure
      }
      const json = await resp.json();
      const content = parseContent(json);
      if (content === null || !content.trim()) {
        // HTTP-200 with empty content: reasoning variants exhaust their
        // token budget on invisible reasoning. Retryable availability
        // failure — NOT a valid reply.
        throw new Error("LLM_EMPTY_REPLY");
      }
      const meta = json as { model?: string; provider?: string };
      return {
        content,
        provenance: {
          endpoint,
          modelRequested: requestedModel,
          modelServed: meta.model,
          providerOrigin: meta.provider,
          ...(candidate.poolProvider !== undefined ? { poolProvider: candidate.poolProvider } : {}),
          temperature: opts.temperature,
          maxTokens: opts.maxTokens,
        },
      };
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") {
        lastErr = new Error("MODEL_TIMEOUT");
      } else {
        lastErr = err;
        if (!(err instanceof Error && isTransientLlmError(err))) {
          // Non-transient parse/shape error — surface immediately.
          throw err;
        }
      }
    } finally {
      clearTimeout(timeoutId);
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error("LLM call failed");
}

export async function callLlm(
  model: string,
  systemPrompt: string,
  userPrompt: string,
  config: LlmConfig = {},
  timeoutMs: number = 30000
): Promise<LlmResult> {
  const temperature = config.temperature ?? 0.2;
  // Headroom above bare-JSON needs: free-tier models (e.g. reasoning
  // variants) spend budget on invisible reasoning BEFORE content — a 512
  // cap routinely yields an empty reply for a one-line action.
  const maxTokens = config.maxTokens ?? 1024;

  return completeWithPool(
    model,
    (servingModel) =>
      JSON.stringify({
        model: servingModel,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature,
        max_tokens: maxTokens,
      }),
    (json) => {
      const choices = (json as { choices?: Array<{ message?: { content?: string | null } }> }).choices;
      return choices?.[0]?.message?.content ?? null;
    },
    { requireConfigured: true, timeoutMs, temperature, maxTokens }
  );
}

/**
 * P1-AUDIT-2 Phase F — multimodal completion for the vision-only adapter.
 * Identical config/env/timeout/provenance semantics to callLlm(), with one
 * image (data: URL) embedded as an OpenAI-compatible image_url content part
 * in the user message. Text and image ride the SAME user turn so the
 * screenshot is contextualized by the prompt text.
 */
export async function callLlmVision(
  model: string,
  systemPrompt: string,
  userPrompt: string,
  imageDataUrl: string,
  config: LlmConfig = {},
  timeoutMs: number = 45000
): Promise<LlmResult> {
  const temperature = config.temperature ?? 0.2;
  // Vision payloads are large; default headroom above the text-only floor —
  // reasoning variants burn invisible tokens before the visible content.
  const maxTokens = config.maxTokens ?? 2048;

  return completeWithPool(
    model,
    (servingModel) =>
      JSON.stringify({
        model: servingModel,
        messages: [
          { role: "system", content: systemPrompt },
          {
            role: "user",
            content: [
              { type: "text", text: userPrompt },
              { type: "image_url", image_url: { url: imageDataUrl } },
            ],
          },
        ],
        temperature,
        max_tokens: maxTokens,
      }),
    (json) => {
      const choices = (json as { choices?: Array<{ message?: { content?: string | null } }> }).choices;
      return choices?.[0]?.message?.content ?? null;
    },
    { requireConfigured: true, timeoutMs, temperature, maxTokens }
  );
}
